### ISSUE TITLE
Bugged Jingles, Plugin breaks, Jingle Overrides.

### ISSUE THREAD

**Issue by Losermac** [Tayaramisu/JingleJingle#4]
1. Bugged Jingles:
Currently there are issues with certain Jingles that are not working properly. 

Each time you complete a Falador Diary Task it plays the Agility Pyramid jingle instead of any other Jingle you assign it on either Desert or Falador Diary Tasks. 
The Diary Completion Jingle works fine for both however. 

No matter what you configure with Kourend, or Lumbridge & Draynor Diary Tasks it always plays nothing. 

2. Plugin breaks:
They're some issues where the Plugin can break things, or break itself.

If you are currently playing any Music Tracks while the plugin Jingle goes off, it has a chance to stop the current Track from playing. 
It can also sometimes break the entire Plugin resulting in needing to either having to Logout, uninstall and reinstall the Plugin, or both to fix it.

4. Jingle Overrides:
Some Jingles need to override other in-game jingles.

The plugin currently cannot override Karamja's Diary Task original jingle, or Combat Task Completions' original jingle. This results in making those Jingles useless as they both play two jingles at once making it all sound like a mess. 

I wanted to submit these just to bring up some current issues with the Plugin to the creators. These issues are not game breaking or serious in anyway. 
They also may be a problem with my client only as well but I'm going to submit this anyway just in case.

**Comment by TaylorAbraham** [comment]
Thanks very much for the detailed report, I'll look into these :)

**Comment by ghost** [comment]
Thanks for the detailed bug report, I'll look into these :)

**Comment by ghost** [comment]
Do you have any details regarding the "sometimes breaks the entire plugin"? I haven't encountered that myself and I'm curious if there's any way to repro

**Comment by ghost** [comment]
Resolved as many of these as are possible within the confines of Runelite. Some, like the sometimes stopping music tracks, is unfortunately an innate quirk with how runelite allows for playing/pausing tracks.
